name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: bash ./gradlew assemble

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Update-Release
          path: "app/build/outputs/apk/release/*.apk"
          compression-level: 9

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Updater-Debug
          path: "app/build/outputs/apk/debug/*.apk"
          compression-level: 9
